package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class AttachGroupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttachGroupAllPropertiesEquals(AttachGroup expected, AttachGroup actual) {
        assertAttachGroupAutoGeneratedPropertiesEquals(expected, actual);
        assertAttachGroupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttachGroupAllUpdatablePropertiesEquals(AttachGroup expected, AttachGroup actual) {
        assertAttachGroupUpdatableFieldsEquals(expected, actual);
        assertAttachGroupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttachGroupAutoGeneratedPropertiesEquals(AttachGroup expected, AttachGroup actual) {
        assertThat(expected)
            .as("Verify AttachGroup auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttachGroupUpdatableFieldsEquals(AttachGroup expected, AttachGroup actual) {
        assertThat(expected)
            .as("Verify AttachGroup relevant properties")
            .satisfies(
                e ->
                    assertThat(e.getCreatedAt())
                        .as("check createdAt")
                        .usingComparator(zonedDataTimeSameInstant)
                        .isEqualTo(actual.getCreatedAt())
            )
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttachGroupUpdatableRelationshipsEquals(AttachGroup expected, AttachGroup actual) {
        assertThat(expected)
            .as("Verify AttachGroup relationships")
            .satisfies(e -> assertThat(e.getPost()).as("check post").isEqualTo(actual.getPost()));
    }
}
